server:
  port: 8080


spring:
  application:
    name: gateway
    
  cloud:
    gateway:
      routes:
        - id: course
          uri: lb://course
          predicates:
            - Path=/course/**
          filters:
            - PrefixPath=/v1/admin
            - AddResponseHeader=X-Powered-By,f4biu Gateway Service Test
        - id: registry
          uri: lb://registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**
  main:
    web-application-type: reactive

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info